development:
  adapter: postgresql
  database: simple-app-dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: simple-app-test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: simple-app-prod
  pool: 5
  timeout: 5000
